### ISSUE TITLE
New portfolio's refresh :technologist::construction_worker:

### ISSUE THREAD

**Issue by mjesusoj** [mjesusoj/portfolio#8]
### Add to the project this tool 
> Tailwind CSS UI for Tailwind CSS UI Components, Blocks and Templates
[Go to Tailgrids - tailgrids.com ](https://tailgrids.com/)

**Comment by mjesusoj** [comment]
### TODO 🧑‍💻

- [ ] Add portfolio's logo
- [ ] Color of links
- [ ] Continue with other sections
- [ ] Responsive
- [ ] Implement new Footer: CV, contact
